### ISSUE TITLE
.asec file error

### ISSUE THREAD

**Issue by Gad** [TinyCircuits/TinyCircuits-TinyScreen-Android-App#1]
Hi,
This doesn't seem to install ok on my android 4.2.2 
What was the android version it is intended for ?
thx
Gad

**Comment by TinyCircuits** [comment]
HI Gad – sorry for the confusion, this requires Android 4.3 or higher since that’s the first version that supports Bluetooth Low Energy.

Thanks,

TinyCircuits

**Comment by Gad** [comment]
Hi,
Yes indeed I came to that conclusion too late ...
Let see if I can get hold of one :)
Thanks
Gilles
