### ISSUE TITLE
App Stops working when connection attempted.

### ISSUE THREAD

**Issue by IRamsey** [TinyCircuits/TinyCircuits-TinyScreen-Android-App#2]
I get the "Unfortunately, TinyCircuits BLE Conduit has stopped" error when trying connect to the tinyduino. I am using the app on an HTC One M8.

**Comment by jango2104** [comment]
ikr so frustrating

**Comment by bsanth** [comment]
Hitting the same issue on Oneplus One. Can we get a fix???

**Comment by eekcage** [comment]
Same 4.

 FATAL EXCEPTION: main
    Process: com.tinycircuits.tinycircuitsble, PID: 13906
    java.lang.RuntimeException: Unable to instantiate service com.tinycircuits.tinycircuitsble.bluetoothservice.BluetoothLeService: java.lang.NullPointerException
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2581)
            at com.tinycircuits.tinycircuitsble.bluetoothservice.BluetoothLeService.<init>(BluetoothLeService.java:44)

**Comment by eekcage** [comment]
check out baritonehands/TinyCircuits-TinyScreen-Android-App fork. His edits in BluetoothLeService.java fixed it

**Comment by TinyCircuits** [comment]
The repository has been updated to reflect the correction made by @baritonehands.
